### PR TITLE
GOST89 ParamSet Z (OpenSSL compliant) support

### PR DESCRIPTION
**Pull request by pedroalbanese**

### CODE REVIEW

**Comment by rmuch** [comment]
Thanks for the contribution, I will do some verification of that S-box, but I have no objection to merging if it's useful.

Out of curiosity, are you using this library for anything interesting that you would like to share?

**Comment by gruzdev** [comment]
@rmuch, hello! The request is misleading. Another sbox alone can't turn gost89 into Magma. The key and the data should be modified. Take a look [here](https://github.com/ddulesov/gogost/blob/244d93c2001dc3a66a2e243c807ec359da903da2/gost341264/cipher.go).

**Comment by pedroalbanese** [comment]
@gruzdev No, Magma is not GOST89, but based on it. Now the GOST89 block cipher is called Magma. Sbox ParamSetZ makes your library compatible with OpenSSL, gost89(cfb) and gost89-cbc. 

See: https://github.com/pedroalbanese/edgetk

GOST 28147-89 (Magma):
https://en.wikipedia.org/wiki/GOST_(block_cipher)

**Comment by gruzdev** [comment]
Hi! English wikipedia entry misleading as well. Try the [russian](https://ru.wikipedia.org/w/index.php?title=%D0%93%D0%9E%D0%A1%D0%A2_28147-89&section=2#%D0%9C%D0%B0%D0%B3%D0%BC%D0%B0) one. Nowdays Magma is [RFC 8891](https://tools.ietf.org/html/rfc8891) or [ГОСТ 34.12-2018](https://ru.wikipedia.org/wiki/%D0%93%D0%9E%D0%A1%D0%A2_34.12-2018).

**Comment by pedroalbanese** [comment]
@gruzdev I was wrong to mention "Magma", but that's where Sbox was ([RFC 8891](https://tools.ietf.org/html/rfc8891)), that is, the implementation of OpenSSL and LibreSSL are about the GOST89 cipher with Sbox of Magma. I got the title wrong, but is the right implementation.

**Pull request merged**
